package main

var quotes = []string{
	"The quick brown fox jumps over the lazy dog.",
	"All that glitters is not gold.",
	"To be or not to be, that is the question.",
	"In the middle of difficulty lies opportunity.",
	"Life is what happens when you're busy making other plans.",
	"The only way to do great work is to love what you do.",
	"It does not matter how slowly you go as long as you do not stop.",
	"Success is not final, failure is not fatal: It is the courage to continue that counts.",
	"Believe you can and you're halfway there.",
	"The future belongs to those who believe in the beauty of their dreams.",
	"The only person you are destined to become is the person you decide to be.",
	"The best way to predict the future is to create it.",
	"The only limit to our realization of tomorrow will be our doubts of today.",
	"Every moment is a fresh beginning.",
	"Happiness is not something ready-made, it comes from your own actions.",
	"The journey of a thousand miles begins with a single step.",
	"A smooth sea never made a skilled sailor.",
	"Knowledge speaks, but wisdom listens.",
	"Be the change that you wish to see in the world.",
	"What we think, we become.",
	"The greatest glory in living lies not in never falling, but in rising every time we fall.",
	"Two roads diverged in a wood, and I took the one less traveled by.",
	"When the going gets tough, the tough get going.",
	"Yesterday is history, tomorrow is a mystery, today is a gift.",
	"Life is 10% what happens to us and 90% how we react to it.",
}
